export const MAX_SMS_LENGTH = 159;
export const MIN_SMS_LENGTH = 3;

export const  NOTIFY_RECIEPIENT_TYPE_CUSTOM = "NOTIFY_RECIEPIENT_TYPE_CUSTOM";
export const NOTIFY_RECIEPIENT_TYPE_CONTACT_GROUP = "NOTIFY_RECIEPIENT_TYPE_CONTACT_GROUP";
export const NOTIFY_RECIEPIENT_TYPE_CHANNEL = "NOTIFY_RECIEPIENT_TYPE_CHANNEL";